import type { ContentTopic } from "@/types/news-platform";

export interface TopicKeywordRule {
  topic: ContentTopic;
  /** Whole-word or phrase patterns (case-insensitive). */
  keywords: string[];
  /** Multiplier for title/summary matches. */
  titleBoost?: number;
}

export const TOPIC_KEYWORD_RULES: TopicKeywordRule[] = [
  {
    topic: "Politics",
    keywords: [
      "election",
      "president",
      "congress",
      "senate",
      "parliament",
      "minister",
      "democrat",
      "republican",
      "policy",
      "legislation",
      "vote",
      "campaign",
      "white house",
      "governor",
      "political",
    ],
    titleBoost: 2,
  },
  {
    topic: "Finance",
    keywords: [
      "stock",
      "market",
      "investor",
      "bank",
      "fed",
      "inflation",
      "gdp",
      "earnings",
      "revenue",
      "profit",
      "bond",
      "trading",
      "wall street",
      "interest rate",
      "cryptocurrency",
      "ipo",
    ],
    titleBoost: 2,
  },
  {
    topic: "Science",
    keywords: [
      "research",
      "scientist",
      "study",
      "nasa",
      "space",
      "climate",
      "physics",
      "biology",
      "experiment",
      "discovery",
      "peer-reviewed",
      "laboratory",
      "species",
      "universe",
    ],
    titleBoost: 1.5,
  },
  {
    topic: "Health",
    keywords: [
      "health",
      "hospital",
      "patient",
      "disease",
      "vaccine",
      "fda",
      "medical",
      "doctor",
      "virus",
      "cancer",
      "treatment",
      "symptom",
      "mental health",
      "pandemic",
      "pharmaceutical",
    ],
    titleBoost: 2,
  },
  {
    topic: "Technology",
    keywords: [
      "tech",
      "software",
      "ai",
      "artificial intelligence",
      "startup",
      "cyber",
      "hack",
      "apple",
      "google",
      "microsoft",
      "chip",
      "semiconductor",
      "app",
      "data breach",
      "robot",
    ],
    titleBoost: 2,
  },
  {
    topic: "International",
    keywords: [
      "foreign",
      "global",
      "international",
      "nato",
      "united nations",
      "embassy",
      "sanctions",
      "war",
      "conflict",
      "border",
      "refugee",
      "diplomat",
      "overseas",
      "ukraine",
      "china",
      "europe",
    ],
    titleBoost: 1.5,
  },
  {
    topic: "Crime",
    keywords: [
      "crime",
      "police",
      "arrest",
      "murder",
      "shooting",
      "robbery",
      "fraud",
      "investigation",
      "suspect",
      "trial",
      "prison",
      "indictment",
      "prosecutor",
      "victim",
      "stolen",
    ],
    titleBoost: 2,
  },
  {
    topic: "Entertainment",
    keywords: [
      "movie",
      "film",
      "celebrity",
      "actor",
      "music",
      "album",
      "concert",
      "tv",
      "series",
      "hollywood",
      "box office",
      "streaming",
      "award",
      "grammy",
      "oscar",
    ],
    titleBoost: 2,
  },
  {
    topic: "Sports",
    keywords: [
      "sports",
      "game",
      "team",
      "player",
      "coach",
      "league",
      "nfl",
      "nba",
      "mlb",
      "soccer",
      "football",
      "basketball",
      "championship",
      "tournament",
      "score",
      "olympic",
    ],
    titleBoost: 2,
  },
];
