import type { ArticleSource } from "@/types/news-platform";
import type { RssFeedRegistryEntry } from "./rss/registry";

/**
 * Major US & world news organizations — always included for ingest and reliability tracking.
 */
export const MAJOR_US_WORLD_SOURCES: ArticleSource[] = [
  { id: "s1", name: "Reuters", domain: "reuters.com", bias: "center", reliability: 96, approved: true },
  { id: "s2", name: "Associated Press", domain: "apnews.com", bias: "center", reliability: 95, approved: true },
  { id: "s3", name: "BBC News", domain: "bbc.com", bias: "center", reliability: 92, approved: true },
  { id: "s4", name: "The New York Times", domain: "nytimes.com", bias: "center-left", reliability: 88, approved: true },
  { id: "s5", name: "The Wall Street Journal", domain: "wsj.com", bias: "center-right", reliability: 89, approved: true },
  { id: "s6", name: "The Guardian", domain: "theguardian.com", bias: "center-left", reliability: 85, approved: true },
  { id: "s7", name: "Financial Times", domain: "ft.com", bias: "center", reliability: 91, approved: true },
  { id: "s8", name: "Bloomberg", domain: "bloomberg.com", bias: "center", reliability: 90, approved: true },
  { id: "s9", name: "NPR", domain: "npr.org", bias: "center-left", reliability: 87, approved: true },
  { id: "s10", name: "Al Jazeera", domain: "aljazeera.com", bias: "center-left", reliability: 80, approved: true },
  { id: "s11", name: "Politico", domain: "politico.com", bias: "center", reliability: 82, approved: true },
  { id: "s12", name: "Axios", domain: "axios.com", bias: "center", reliability: 83, approved: true },
  { id: "fox", name: "Fox News", domain: "foxnews.com", bias: "right", reliability: 72, approved: true },
  { id: "abc", name: "ABC News", domain: "abcnews.go.com", bias: "center-left", reliability: 80, approved: true },
  { id: "nbc", name: "NBC News", domain: "nbcnews.com", bias: "center-left", reliability: 78, approved: true },
  { id: "cbs", name: "CBS News", domain: "cbsnews.com", bias: "center-left", reliability: 79, approved: true },
  { id: "cnn", name: "CNN", domain: "cnn.com", bias: "center-left", reliability: 75, approved: true },
  { id: "usnews", name: "U.S. News & World Report", domain: "usnews.com", bias: "center", reliability: 76, approved: true },
  { id: "nypost", name: "New York Post", domain: "nypost.com", bias: "right", reliability: 68, approved: true },
  { id: "washpost", name: "The Washington Post", domain: "washingtonpost.com", bias: "center-left", reliability: 84, approved: true },
  { id: "latimes", name: "Los Angeles Times", domain: "latimes.com", bias: "center-left", reliability: 82, approved: true },
  { id: "usatoday", name: "USA Today", domain: "usatoday.com", bias: "center", reliability: 77, approved: true },
  { id: "newsweek", name: "Newsweek", domain: "newsweek.com", bias: "center", reliability: 74, approved: true },
  { id: "time", name: "TIME", domain: "time.com", bias: "center-left", reliability: 78, approved: true },
  { id: "economist", name: "The Economist", domain: "economist.com", bias: "center", reliability: 88, approved: true },
];

/** RSS feeds for major outlets (merged into registry on every load). */
export const MAJOR_US_WORLD_RSS_FEEDS: RssFeedRegistryEntry[] = [
  {
    id: "fox-latest",
    name: "Fox News",
    domain: "foxnews.com",
    feedUrl: "https://moxie.foxnews.com/google-publisher/latest.xml",
    sourceId: "fox",
    category: "Politics",
    language: "en",
    country: "US",
    reliability: 72,
    enabled: true,
    contentPolicy: "feed_summary_only",
    includeImage: true,
    maxItemsPerFetch: 25,
  },
  {
    id: "abc-top",
    name: "ABC News",
    domain: "abcnews.go.com",
    feedUrl: "https://abcnews.go.com/abcnews/topstories",
    sourceId: "abc",
    category: "General",
    language: "en",
    country: "US",
    reliability: 80,
    enabled: true,
    contentPolicy: "feed_summary_only",
    includeImage: true,
    maxItemsPerFetch: 25,
  },
  {
    id: "cbs-main",
    name: "CBS News",
    domain: "cbsnews.com",
    feedUrl: "https://www.cbsnews.com/latest/rss/main",
    sourceId: "cbs",
    category: "General",
    language: "en",
    country: "US",
    reliability: 79,
    enabled: true,
    contentPolicy: "feed_summary_only",
    includeImage: true,
    maxItemsPerFetch: 25,
  },
  {
    id: "usnews-top",
    name: "U.S. News",
    domain: "usnews.com",
    feedUrl: "https://www.usnews.com/rss/news",
    sourceId: "usnews",
    category: "General",
    language: "en",
    country: "US",
    reliability: 76,
    enabled: true,
    contentPolicy: "feed_summary_only",
    includeImage: true,
    maxItemsPerFetch: 20,
  },
  {
    id: "wsj-world",
    name: "Wall Street Journal",
    domain: "wsj.com",
    feedUrl: "https://feeds.a.dj.com/rss/RSSWorldNews.xml",
    sourceId: "s5",
    category: "World",
    language: "en",
    country: "US",
    reliability: 89,
    enabled: true,
    contentPolicy: "feed_summary_only",
    includeImage: false,
    maxItemsPerFetch: 20,
  },
  {
    id: "nyt-home",
    name: "NY Times",
    domain: "nytimes.com",
    feedUrl: "https://rss.nytimes.com/services/xml/rss/nyt/HomePage.xml",
    sourceId: "s4",
    category: "General",
    language: "en",
    country: "US",
    reliability: 88,
    enabled: true,
    contentPolicy: "feed_summary_only",
    includeImage: true,
    maxItemsPerFetch: 25,
  },
  {
    id: "nypost-feed",
    name: "New York Post",
    domain: "nypost.com",
    feedUrl: "https://nypost.com/feed/",
    sourceId: "nypost",
    category: "General",
    language: "en",
    country: "US",
    reliability: 68,
    enabled: true,
    contentPolicy: "feed_summary_only",
    includeImage: true,
    maxItemsPerFetch: 20,
  },
  {
    id: "washpost-politics",
    name: "Washington Post",
    domain: "washingtonpost.com",
    feedUrl: "https://feeds.washingtonpost.com/rss/politics",
    sourceId: "washpost",
    category: "Politics",
    language: "en",
    country: "US",
    reliability: 84,
    enabled: true,
    contentPolicy: "feed_summary_only",
    includeImage: true,
    maxItemsPerFetch: 20,
  },
  {
    id: "usatoday-news",
    name: "USA Today",
    domain: "usatoday.com",
    feedUrl: "https://rssfeeds.usatoday.com/usatoday-NewsTopStories",
    sourceId: "usatoday",
    category: "General",
    language: "en",
    country: "US",
    reliability: 77,
    enabled: true,
    contentPolicy: "feed_summary_only",
    includeImage: true,
    maxItemsPerFetch: 20,
  },
];

export const MAJOR_PUBLISHER_DOMAIN_RELIABILITY: Record<string, number> = Object.fromEntries(
  MAJOR_US_WORLD_SOURCES.map((s) => [s.domain, s.reliability]),
);
