/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StoriesRouteImport } from './routes/stories'
import { Route as SourcesRouteImport } from './routes/sources'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PipelineRouteImport } from './routes/pipeline'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AnalyzeRouteImport } from './routes/analyze'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AnalyzeIndexRouteImport } from './routes/analyze.index'
import { Route as StoriesClusterIdRouteImport } from './routes/stories.$clusterId'
import { Route as ConsensusClusterIdRouteImport } from './routes/consensus.$clusterId'
import { Route as CompareClusterIdRouteImport } from './routes/compare.$clusterId'
import { Route as ClaimsClaimIdRouteImport } from './routes/claims.$claimId'
import { Route as ApiHealthRouteImport } from './routes/api.health'
import { Route as AnalyzeResultsRouteImport } from './routes/analyze.results'
import { Route as AdminSourcesRouteImport } from './routes/admin.sources'
import { Route as StoriesClusterIdArticleIdRouteImport } from './routes/stories.$clusterId.$articleId'
import { Route as ApiStoriesTop100RouteImport } from './routes/api.stories.top-100'
import { Route as ApiStoriesIdRouteImport } from './routes/api.stories.$id'
import { Route as ApiArticlesIdRouteImport } from './routes/api.articles.$id'
import { Route as ApiAnalyzeUrlRouteImport } from './routes/api.analyze.url'
import { Route as ApiAnalyzeTextRouteImport } from './routes/api.analyze.text'
import { Route as ApiAnalyzeArticleRouteImport } from './routes/api.analyze.article'
import { Route as ApiExplainEntityTypeEntityIdRouteImport } from './routes/api.explain.$entityType.$entityId'
import { Route as ApiDebugArticleIdRouteImport } from './routes/api.debug.article.$id'
import { Route as ApiAnalyzeStatusRequestIdRouteImport } from './routes/api.analyze.status.$requestId'

const StoriesRoute = StoriesRouteImport.update({
  id: '/stories',
  path: '/stories',
  getParentRoute: () => rootRouteImport,
} as any)
const SourcesRoute = SourcesRouteImport.update({
  id: '/sources',
  path: '/sources',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PipelineRoute = PipelineRouteImport.update({
  id: '/pipeline',
  path: '/pipeline',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyzeRoute = AnalyzeRouteImport.update({
  id: '/analyze',
  path: '/analyze',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyzeIndexRoute = AnalyzeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AnalyzeRoute,
} as any)
const StoriesClusterIdRoute = StoriesClusterIdRouteImport.update({
  id: '/$clusterId',
  path: '/$clusterId',
  getParentRoute: () => StoriesRoute,
} as any)
const ConsensusClusterIdRoute = ConsensusClusterIdRouteImport.update({
  id: '/consensus/$clusterId',
  path: '/consensus/$clusterId',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareClusterIdRoute = CompareClusterIdRouteImport.update({
  id: '/compare/$clusterId',
  path: '/compare/$clusterId',
  getParentRoute: () => rootRouteImport,
} as any)
const ClaimsClaimIdRoute = ClaimsClaimIdRouteImport.update({
  id: '/claims/$claimId',
  path: '/claims/$claimId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyzeResultsRoute = AnalyzeResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => AnalyzeRoute,
} as any)
const AdminSourcesRoute = AdminSourcesRouteImport.update({
  id: '/admin/sources',
  path: '/admin/sources',
  getParentRoute: () => rootRouteImport,
} as any)
const StoriesClusterIdArticleIdRoute =
  StoriesClusterIdArticleIdRouteImport.update({
    id: '/$articleId',
    path: '/$articleId',
    getParentRoute: () => StoriesClusterIdRoute,
  } as any)
const ApiStoriesTop100Route = ApiStoriesTop100RouteImport.update({
  id: '/api/stories/top-100',
  path: '/api/stories/top-100',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStoriesIdRoute = ApiStoriesIdRouteImport.update({
  id: '/api/stories/$id',
  path: '/api/stories/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiArticlesIdRoute = ApiArticlesIdRouteImport.update({
  id: '/api/articles/$id',
  path: '/api/articles/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAnalyzeUrlRoute = ApiAnalyzeUrlRouteImport.update({
  id: '/api/analyze/url',
  path: '/api/analyze/url',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAnalyzeTextRoute = ApiAnalyzeTextRouteImport.update({
  id: '/api/analyze/text',
  path: '/api/analyze/text',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAnalyzeArticleRoute = ApiAnalyzeArticleRouteImport.update({
  id: '/api/analyze/article',
  path: '/api/analyze/article',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiExplainEntityTypeEntityIdRoute =
  ApiExplainEntityTypeEntityIdRouteImport.update({
    id: '/api/explain/$entityType/$entityId',
    path: '/api/explain/$entityType/$entityId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiDebugArticleIdRoute = ApiDebugArticleIdRouteImport.update({
  id: '/api/debug/article/$id',
  path: '/api/debug/article/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAnalyzeStatusRequestIdRoute =
  ApiAnalyzeStatusRequestIdRouteImport.update({
    id: '/api/analyze/status/$requestId',
    path: '/api/analyze/status/$requestId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analyze': typeof AnalyzeRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/pipeline': typeof PipelineRoute
  '/pricing': typeof PricingRoute
  '/settings': typeof SettingsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sources': typeof SourcesRoute
  '/stories': typeof StoriesRouteWithChildren
  '/admin/sources': typeof AdminSourcesRoute
  '/analyze/results': typeof AnalyzeResultsRoute
  '/api/health': typeof ApiHealthRoute
  '/claims/$claimId': typeof ClaimsClaimIdRoute
  '/compare/$clusterId': typeof CompareClusterIdRoute
  '/consensus/$clusterId': typeof ConsensusClusterIdRoute
  '/stories/$clusterId': typeof StoriesClusterIdRouteWithChildren
  '/analyze/': typeof AnalyzeIndexRoute
  '/api/analyze/article': typeof ApiAnalyzeArticleRoute
  '/api/analyze/text': typeof ApiAnalyzeTextRoute
  '/api/analyze/url': typeof ApiAnalyzeUrlRoute
  '/api/articles/$id': typeof ApiArticlesIdRoute
  '/api/stories/$id': typeof ApiStoriesIdRoute
  '/api/stories/top-100': typeof ApiStoriesTop100Route
  '/stories/$clusterId/$articleId': typeof StoriesClusterIdArticleIdRoute
  '/api/analyze/status/$requestId': typeof ApiAnalyzeStatusRequestIdRoute
  '/api/debug/article/$id': typeof ApiDebugArticleIdRoute
  '/api/explain/$entityType/$entityId': typeof ApiExplainEntityTypeEntityIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/pipeline': typeof PipelineRoute
  '/pricing': typeof PricingRoute
  '/settings': typeof SettingsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sources': typeof SourcesRoute
  '/stories': typeof StoriesRouteWithChildren
  '/admin/sources': typeof AdminSourcesRoute
  '/analyze/results': typeof AnalyzeResultsRoute
  '/api/health': typeof ApiHealthRoute
  '/claims/$claimId': typeof ClaimsClaimIdRoute
  '/compare/$clusterId': typeof CompareClusterIdRoute
  '/consensus/$clusterId': typeof ConsensusClusterIdRoute
  '/stories/$clusterId': typeof StoriesClusterIdRouteWithChildren
  '/analyze': typeof AnalyzeIndexRoute
  '/api/analyze/article': typeof ApiAnalyzeArticleRoute
  '/api/analyze/text': typeof ApiAnalyzeTextRoute
  '/api/analyze/url': typeof ApiAnalyzeUrlRoute
  '/api/articles/$id': typeof ApiArticlesIdRoute
  '/api/stories/$id': typeof ApiStoriesIdRoute
  '/api/stories/top-100': typeof ApiStoriesTop100Route
  '/stories/$clusterId/$articleId': typeof StoriesClusterIdArticleIdRoute
  '/api/analyze/status/$requestId': typeof ApiAnalyzeStatusRequestIdRoute
  '/api/debug/article/$id': typeof ApiDebugArticleIdRoute
  '/api/explain/$entityType/$entityId': typeof ApiExplainEntityTypeEntityIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analyze': typeof AnalyzeRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/pipeline': typeof PipelineRoute
  '/pricing': typeof PricingRoute
  '/settings': typeof SettingsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sources': typeof SourcesRoute
  '/stories': typeof StoriesRouteWithChildren
  '/admin/sources': typeof AdminSourcesRoute
  '/analyze/results': typeof AnalyzeResultsRoute
  '/api/health': typeof ApiHealthRoute
  '/claims/$claimId': typeof ClaimsClaimIdRoute
  '/compare/$clusterId': typeof CompareClusterIdRoute
  '/consensus/$clusterId': typeof ConsensusClusterIdRoute
  '/stories/$clusterId': typeof StoriesClusterIdRouteWithChildren
  '/analyze/': typeof AnalyzeIndexRoute
  '/api/analyze/article': typeof ApiAnalyzeArticleRoute
  '/api/analyze/text': typeof ApiAnalyzeTextRoute
  '/api/analyze/url': typeof ApiAnalyzeUrlRoute
  '/api/articles/$id': typeof ApiArticlesIdRoute
  '/api/stories/$id': typeof ApiStoriesIdRoute
  '/api/stories/top-100': typeof ApiStoriesTop100Route
  '/stories/$clusterId/$articleId': typeof StoriesClusterIdArticleIdRoute
  '/api/analyze/status/$requestId': typeof ApiAnalyzeStatusRequestIdRoute
  '/api/debug/article/$id': typeof ApiDebugArticleIdRoute
  '/api/explain/$entityType/$entityId': typeof ApiExplainEntityTypeEntityIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analyze'
    | '/dashboard'
    | '/login'
    | '/pipeline'
    | '/pricing'
    | '/settings'
    | '/sitemap.xml'
    | '/sources'
    | '/stories'
    | '/admin/sources'
    | '/analyze/results'
    | '/api/health'
    | '/claims/$claimId'
    | '/compare/$clusterId'
    | '/consensus/$clusterId'
    | '/stories/$clusterId'
    | '/analyze/'
    | '/api/analyze/article'
    | '/api/analyze/text'
    | '/api/analyze/url'
    | '/api/articles/$id'
    | '/api/stories/$id'
    | '/api/stories/top-100'
    | '/stories/$clusterId/$articleId'
    | '/api/analyze/status/$requestId'
    | '/api/debug/article/$id'
    | '/api/explain/$entityType/$entityId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/login'
    | '/pipeline'
    | '/pricing'
    | '/settings'
    | '/sitemap.xml'
    | '/sources'
    | '/stories'
    | '/admin/sources'
    | '/analyze/results'
    | '/api/health'
    | '/claims/$claimId'
    | '/compare/$clusterId'
    | '/consensus/$clusterId'
    | '/stories/$clusterId'
    | '/analyze'
    | '/api/analyze/article'
    | '/api/analyze/text'
    | '/api/analyze/url'
    | '/api/articles/$id'
    | '/api/stories/$id'
    | '/api/stories/top-100'
    | '/stories/$clusterId/$articleId'
    | '/api/analyze/status/$requestId'
    | '/api/debug/article/$id'
    | '/api/explain/$entityType/$entityId'
  id:
    | '__root__'
    | '/'
    | '/analyze'
    | '/dashboard'
    | '/login'
    | '/pipeline'
    | '/pricing'
    | '/settings'
    | '/sitemap.xml'
    | '/sources'
    | '/stories'
    | '/admin/sources'
    | '/analyze/results'
    | '/api/health'
    | '/claims/$claimId'
    | '/compare/$clusterId'
    | '/consensus/$clusterId'
    | '/stories/$clusterId'
    | '/analyze/'
    | '/api/analyze/article'
    | '/api/analyze/text'
    | '/api/analyze/url'
    | '/api/articles/$id'
    | '/api/stories/$id'
    | '/api/stories/top-100'
    | '/stories/$clusterId/$articleId'
    | '/api/analyze/status/$requestId'
    | '/api/debug/article/$id'
    | '/api/explain/$entityType/$entityId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyzeRoute: typeof AnalyzeRouteWithChildren
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  PipelineRoute: typeof PipelineRoute
  PricingRoute: typeof PricingRoute
  SettingsRoute: typeof SettingsRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SourcesRoute: typeof SourcesRoute
  StoriesRoute: typeof StoriesRouteWithChildren
  AdminSourcesRoute: typeof AdminSourcesRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ClaimsClaimIdRoute: typeof ClaimsClaimIdRoute
  CompareClusterIdRoute: typeof CompareClusterIdRoute
  ConsensusClusterIdRoute: typeof ConsensusClusterIdRoute
  ApiAnalyzeArticleRoute: typeof ApiAnalyzeArticleRoute
  ApiAnalyzeTextRoute: typeof ApiAnalyzeTextRoute
  ApiAnalyzeUrlRoute: typeof ApiAnalyzeUrlRoute
  ApiArticlesIdRoute: typeof ApiArticlesIdRoute
  ApiStoriesIdRoute: typeof ApiStoriesIdRoute
  ApiStoriesTop100Route: typeof ApiStoriesTop100Route
  ApiAnalyzeStatusRequestIdRoute: typeof ApiAnalyzeStatusRequestIdRoute
  ApiDebugArticleIdRoute: typeof ApiDebugArticleIdRoute
  ApiExplainEntityTypeEntityIdRoute: typeof ApiExplainEntityTypeEntityIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/stories': {
      id: '/stories'
      path: '/stories'
      fullPath: '/stories'
      preLoaderRoute: typeof StoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sources': {
      id: '/sources'
      path: '/sources'
      fullPath: '/sources'
      preLoaderRoute: typeof SourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pipeline': {
      id: '/pipeline'
      path: '/pipeline'
      fullPath: '/pipeline'
      preLoaderRoute: typeof PipelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analyze': {
      id: '/analyze'
      path: '/analyze'
      fullPath: '/analyze'
      preLoaderRoute: typeof AnalyzeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analyze/': {
      id: '/analyze/'
      path: '/'
      fullPath: '/analyze/'
      preLoaderRoute: typeof AnalyzeIndexRouteImport
      parentRoute: typeof AnalyzeRoute
    }
    '/stories/$clusterId': {
      id: '/stories/$clusterId'
      path: '/$clusterId'
      fullPath: '/stories/$clusterId'
      preLoaderRoute: typeof StoriesClusterIdRouteImport
      parentRoute: typeof StoriesRoute
    }
    '/consensus/$clusterId': {
      id: '/consensus/$clusterId'
      path: '/consensus/$clusterId'
      fullPath: '/consensus/$clusterId'
      preLoaderRoute: typeof ConsensusClusterIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare/$clusterId': {
      id: '/compare/$clusterId'
      path: '/compare/$clusterId'
      fullPath: '/compare/$clusterId'
      preLoaderRoute: typeof CompareClusterIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/claims/$claimId': {
      id: '/claims/$claimId'
      path: '/claims/$claimId'
      fullPath: '/claims/$claimId'
      preLoaderRoute: typeof ClaimsClaimIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analyze/results': {
      id: '/analyze/results'
      path: '/results'
      fullPath: '/analyze/results'
      preLoaderRoute: typeof AnalyzeResultsRouteImport
      parentRoute: typeof AnalyzeRoute
    }
    '/admin/sources': {
      id: '/admin/sources'
      path: '/admin/sources'
      fullPath: '/admin/sources'
      preLoaderRoute: typeof AdminSourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stories/$clusterId/$articleId': {
      id: '/stories/$clusterId/$articleId'
      path: '/$articleId'
      fullPath: '/stories/$clusterId/$articleId'
      preLoaderRoute: typeof StoriesClusterIdArticleIdRouteImport
      parentRoute: typeof StoriesClusterIdRoute
    }
    '/api/stories/top-100': {
      id: '/api/stories/top-100'
      path: '/api/stories/top-100'
      fullPath: '/api/stories/top-100'
      preLoaderRoute: typeof ApiStoriesTop100RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stories/$id': {
      id: '/api/stories/$id'
      path: '/api/stories/$id'
      fullPath: '/api/stories/$id'
      preLoaderRoute: typeof ApiStoriesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/articles/$id': {
      id: '/api/articles/$id'
      path: '/api/articles/$id'
      fullPath: '/api/articles/$id'
      preLoaderRoute: typeof ApiArticlesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/analyze/url': {
      id: '/api/analyze/url'
      path: '/api/analyze/url'
      fullPath: '/api/analyze/url'
      preLoaderRoute: typeof ApiAnalyzeUrlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/analyze/text': {
      id: '/api/analyze/text'
      path: '/api/analyze/text'
      fullPath: '/api/analyze/text'
      preLoaderRoute: typeof ApiAnalyzeTextRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/analyze/article': {
      id: '/api/analyze/article'
      path: '/api/analyze/article'
      fullPath: '/api/analyze/article'
      preLoaderRoute: typeof ApiAnalyzeArticleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/explain/$entityType/$entityId': {
      id: '/api/explain/$entityType/$entityId'
      path: '/api/explain/$entityType/$entityId'
      fullPath: '/api/explain/$entityType/$entityId'
      preLoaderRoute: typeof ApiExplainEntityTypeEntityIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/debug/article/$id': {
      id: '/api/debug/article/$id'
      path: '/api/debug/article/$id'
      fullPath: '/api/debug/article/$id'
      preLoaderRoute: typeof ApiDebugArticleIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/analyze/status/$requestId': {
      id: '/api/analyze/status/$requestId'
      path: '/api/analyze/status/$requestId'
      fullPath: '/api/analyze/status/$requestId'
      preLoaderRoute: typeof ApiAnalyzeStatusRequestIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AnalyzeRouteChildren {
  AnalyzeResultsRoute: typeof AnalyzeResultsRoute
  AnalyzeIndexRoute: typeof AnalyzeIndexRoute
}

const AnalyzeRouteChildren: AnalyzeRouteChildren = {
  AnalyzeResultsRoute: AnalyzeResultsRoute,
  AnalyzeIndexRoute: AnalyzeIndexRoute,
}

const AnalyzeRouteWithChildren =
  AnalyzeRoute._addFileChildren(AnalyzeRouteChildren)

interface StoriesClusterIdRouteChildren {
  StoriesClusterIdArticleIdRoute: typeof StoriesClusterIdArticleIdRoute
}

const StoriesClusterIdRouteChildren: StoriesClusterIdRouteChildren = {
  StoriesClusterIdArticleIdRoute: StoriesClusterIdArticleIdRoute,
}

const StoriesClusterIdRouteWithChildren =
  StoriesClusterIdRoute._addFileChildren(StoriesClusterIdRouteChildren)

interface StoriesRouteChildren {
  StoriesClusterIdRoute: typeof StoriesClusterIdRouteWithChildren
}

const StoriesRouteChildren: StoriesRouteChildren = {
  StoriesClusterIdRoute: StoriesClusterIdRouteWithChildren,
}

const StoriesRouteWithChildren =
  StoriesRoute._addFileChildren(StoriesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyzeRoute: AnalyzeRouteWithChildren,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  PipelineRoute: PipelineRoute,
  PricingRoute: PricingRoute,
  SettingsRoute: SettingsRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SourcesRoute: SourcesRoute,
  StoriesRoute: StoriesRouteWithChildren,
  AdminSourcesRoute: AdminSourcesRoute,
  ApiHealthRoute: ApiHealthRoute,
  ClaimsClaimIdRoute: ClaimsClaimIdRoute,
  CompareClusterIdRoute: CompareClusterIdRoute,
  ConsensusClusterIdRoute: ConsensusClusterIdRoute,
  ApiAnalyzeArticleRoute: ApiAnalyzeArticleRoute,
  ApiAnalyzeTextRoute: ApiAnalyzeTextRoute,
  ApiAnalyzeUrlRoute: ApiAnalyzeUrlRoute,
  ApiArticlesIdRoute: ApiArticlesIdRoute,
  ApiStoriesIdRoute: ApiStoriesIdRoute,
  ApiStoriesTop100Route: ApiStoriesTop100Route,
  ApiAnalyzeStatusRequestIdRoute: ApiAnalyzeStatusRequestIdRoute,
  ApiDebugArticleIdRoute: ApiDebugArticleIdRoute,
  ApiExplainEntityTypeEntityIdRoute: ApiExplainEntityTypeEntityIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
