/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StoriesRouteImport } from './routes/stories'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PipelineRouteImport } from './routes/pipeline'
import { Route as MyWritingRouteImport } from './routes/my-writing'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AnalyzeRouteImport } from './routes/analyze'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StoriesClusterIdRouteImport } from './routes/stories.$clusterId'
import { Route as ConsensusClusterIdRouteImport } from './routes/consensus.$clusterId'
import { Route as CompareClusterIdRouteImport } from './routes/compare.$clusterId'
import { Route as ClaimsClaimIdRouteImport } from './routes/claims.$claimId'
import { Route as AnalyzeResultsRouteImport } from './routes/analyze.results'
import { Route as AdminSourcesRouteImport } from './routes/admin.sources'

const StoriesRoute = StoriesRouteImport.update({
  id: '/stories',
  path: '/stories',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PipelineRoute = PipelineRouteImport.update({
  id: '/pipeline',
  path: '/pipeline',
  getParentRoute: () => rootRouteImport,
} as any)
const MyWritingRoute = MyWritingRouteImport.update({
  id: '/my-writing',
  path: '/my-writing',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyzeRoute = AnalyzeRouteImport.update({
  id: '/analyze',
  path: '/analyze',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StoriesClusterIdRoute = StoriesClusterIdRouteImport.update({
  id: '/$clusterId',
  path: '/$clusterId',
  getParentRoute: () => StoriesRoute,
} as any)
const ConsensusClusterIdRoute = ConsensusClusterIdRouteImport.update({
  id: '/consensus/$clusterId',
  path: '/consensus/$clusterId',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareClusterIdRoute = CompareClusterIdRouteImport.update({
  id: '/compare/$clusterId',
  path: '/compare/$clusterId',
  getParentRoute: () => rootRouteImport,
} as any)
const ClaimsClaimIdRoute = ClaimsClaimIdRouteImport.update({
  id: '/claims/$claimId',
  path: '/claims/$claimId',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyzeResultsRoute = AnalyzeResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => AnalyzeRoute,
} as any)
const AdminSourcesRoute = AdminSourcesRouteImport.update({
  id: '/admin/sources',
  path: '/admin/sources',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analyze': typeof AnalyzeRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/my-writing': typeof MyWritingRoute
  '/pipeline': typeof PipelineRoute
  '/pricing': typeof PricingRoute
  '/settings': typeof SettingsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/stories': typeof StoriesRouteWithChildren
  '/admin/sources': typeof AdminSourcesRoute
  '/analyze/results': typeof AnalyzeResultsRoute
  '/claims/$claimId': typeof ClaimsClaimIdRoute
  '/compare/$clusterId': typeof CompareClusterIdRoute
  '/consensus/$clusterId': typeof ConsensusClusterIdRoute
  '/stories/$clusterId': typeof StoriesClusterIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analyze': typeof AnalyzeRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/my-writing': typeof MyWritingRoute
  '/pipeline': typeof PipelineRoute
  '/pricing': typeof PricingRoute
  '/settings': typeof SettingsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/stories': typeof StoriesRouteWithChildren
  '/admin/sources': typeof AdminSourcesRoute
  '/analyze/results': typeof AnalyzeResultsRoute
  '/claims/$claimId': typeof ClaimsClaimIdRoute
  '/compare/$clusterId': typeof CompareClusterIdRoute
  '/consensus/$clusterId': typeof ConsensusClusterIdRoute
  '/stories/$clusterId': typeof StoriesClusterIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analyze': typeof AnalyzeRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/my-writing': typeof MyWritingRoute
  '/pipeline': typeof PipelineRoute
  '/pricing': typeof PricingRoute
  '/settings': typeof SettingsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/stories': typeof StoriesRouteWithChildren
  '/admin/sources': typeof AdminSourcesRoute
  '/analyze/results': typeof AnalyzeResultsRoute
  '/claims/$claimId': typeof ClaimsClaimIdRoute
  '/compare/$clusterId': typeof CompareClusterIdRoute
  '/consensus/$clusterId': typeof ConsensusClusterIdRoute
  '/stories/$clusterId': typeof StoriesClusterIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analyze'
    | '/dashboard'
    | '/login'
    | '/my-writing'
    | '/pipeline'
    | '/pricing'
    | '/settings'
    | '/sitemap.xml'
    | '/stories'
    | '/admin/sources'
    | '/analyze/results'
    | '/claims/$claimId'
    | '/compare/$clusterId'
    | '/consensus/$clusterId'
    | '/stories/$clusterId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analyze'
    | '/dashboard'
    | '/login'
    | '/my-writing'
    | '/pipeline'
    | '/pricing'
    | '/settings'
    | '/sitemap.xml'
    | '/stories'
    | '/admin/sources'
    | '/analyze/results'
    | '/claims/$claimId'
    | '/compare/$clusterId'
    | '/consensus/$clusterId'
    | '/stories/$clusterId'
  id:
    | '__root__'
    | '/'
    | '/analyze'
    | '/dashboard'
    | '/login'
    | '/my-writing'
    | '/pipeline'
    | '/pricing'
    | '/settings'
    | '/sitemap.xml'
    | '/stories'
    | '/admin/sources'
    | '/analyze/results'
    | '/claims/$claimId'
    | '/compare/$clusterId'
    | '/consensus/$clusterId'
    | '/stories/$clusterId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyzeRoute: typeof AnalyzeRouteWithChildren
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  MyWritingRoute: typeof MyWritingRoute
  PipelineRoute: typeof PipelineRoute
  PricingRoute: typeof PricingRoute
  SettingsRoute: typeof SettingsRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  StoriesRoute: typeof StoriesRouteWithChildren
  AdminSourcesRoute: typeof AdminSourcesRoute
  ClaimsClaimIdRoute: typeof ClaimsClaimIdRoute
  CompareClusterIdRoute: typeof CompareClusterIdRoute
  ConsensusClusterIdRoute: typeof ConsensusClusterIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/stories': {
      id: '/stories'
      path: '/stories'
      fullPath: '/stories'
      preLoaderRoute: typeof StoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pipeline': {
      id: '/pipeline'
      path: '/pipeline'
      fullPath: '/pipeline'
      preLoaderRoute: typeof PipelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-writing': {
      id: '/my-writing'
      path: '/my-writing'
      fullPath: '/my-writing'
      preLoaderRoute: typeof MyWritingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analyze': {
      id: '/analyze'
      path: '/analyze'
      fullPath: '/analyze'
      preLoaderRoute: typeof AnalyzeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stories/$clusterId': {
      id: '/stories/$clusterId'
      path: '/$clusterId'
      fullPath: '/stories/$clusterId'
      preLoaderRoute: typeof StoriesClusterIdRouteImport
      parentRoute: typeof StoriesRoute
    }
    '/consensus/$clusterId': {
      id: '/consensus/$clusterId'
      path: '/consensus/$clusterId'
      fullPath: '/consensus/$clusterId'
      preLoaderRoute: typeof ConsensusClusterIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare/$clusterId': {
      id: '/compare/$clusterId'
      path: '/compare/$clusterId'
      fullPath: '/compare/$clusterId'
      preLoaderRoute: typeof CompareClusterIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/claims/$claimId': {
      id: '/claims/$claimId'
      path: '/claims/$claimId'
      fullPath: '/claims/$claimId'
      preLoaderRoute: typeof ClaimsClaimIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analyze/results': {
      id: '/analyze/results'
      path: '/results'
      fullPath: '/analyze/results'
      preLoaderRoute: typeof AnalyzeResultsRouteImport
      parentRoute: typeof AnalyzeRoute
    }
    '/admin/sources': {
      id: '/admin/sources'
      path: '/admin/sources'
      fullPath: '/admin/sources'
      preLoaderRoute: typeof AdminSourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AnalyzeRouteChildren {
  AnalyzeResultsRoute: typeof AnalyzeResultsRoute
}

const AnalyzeRouteChildren: AnalyzeRouteChildren = {
  AnalyzeResultsRoute: AnalyzeResultsRoute,
}

const AnalyzeRouteWithChildren =
  AnalyzeRoute._addFileChildren(AnalyzeRouteChildren)

interface StoriesRouteChildren {
  StoriesClusterIdRoute: typeof StoriesClusterIdRoute
}

const StoriesRouteChildren: StoriesRouteChildren = {
  StoriesClusterIdRoute: StoriesClusterIdRoute,
}

const StoriesRouteWithChildren =
  StoriesRoute._addFileChildren(StoriesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyzeRoute: AnalyzeRouteWithChildren,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  MyWritingRoute: MyWritingRoute,
  PipelineRoute: PipelineRoute,
  PricingRoute: PricingRoute,
  SettingsRoute: SettingsRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  StoriesRoute: StoriesRouteWithChildren,
  AdminSourcesRoute: AdminSourcesRoute,
  ClaimsClaimIdRoute: ClaimsClaimIdRoute,
  CompareClusterIdRoute: CompareClusterIdRoute,
  ConsensusClusterIdRoute: ConsensusClusterIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
